name: Test PHP MySQL Connection

on:
  workflow_dispatch: # manual trigger

jobs:
  run-db-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHP DB Test
        run: php test_db.php
